### ISSUE TITLE
python error when adding a layer to a repo with the button "add layer to repository"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#103]
Does not happen with the "add layer to repository" available by right clicking the layer in the layers panel:

Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/navigatordialog.py", line 285, in addLayer
    self.versionsTree.updateCurrentBranchItem()
AttributeError: 'HistoryViewer' object has no attribute 'updateCurrentBranchItem'

**Comment by gioman** [comment]
Now I get 

Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/navigatordialog.py", line 282, in addLayer
    dlg = ImportDialog(self, repo = self.currentRepo)
  File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/importdialog.py", line 56, in __init__
    self.initGui()
  File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/importdialog.py", line 84, in initGui
    self.branches = self.repo.branches() if self.repo is not None else repos[0].branches()
IndexError: list index out of range

**Comment by gioman** [comment]
> Now I get
> 
> Traceback (most recent call last):
> File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/navigatordialog.py", line 282, in addLayer
> dlg = ImportDialog(self, repo = self.currentRepo)
> File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/importdialog.py", line 56, in init
> self.initGui()
> File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/importdialog.py", line 84, in initGui
> self.branches = self.repo.branches() if self.repo is not None else repos[0].branches()
> IndexError: list index out of range

I cannot replicate anymore... if the error message does not point to something obvious this could be closed.

**Comment by volaya** [comment]
looks related to the error we just solved wth unpopulated repo trees. I am closing it, but please reopen if that reappears
