### ISSUE TITLE
How to build and debug plugin in qgis?

### ISSUE THREAD

**Issue by tuannvapj** [boundlessgeo/qgis-geogiglight-plugin#121]
Hi everyone, I have reference the document and repository on git https://github.com/planetfederal/qgis-geogiglight-plugin
and run successfully. But when I want to edit, update this features to work as particular need. Could you all please tell me
"How to build and debug plugin? or their is any document for build and debug"
Sincerely

**Comment by koyo-jakanees** [comment]
Hello @tuannvapj the repository [referenced](https://github.com/planetfederal/qgis-geogiglight-plugin) has guidelines on how to build and use this plugin. the required prerequisites for dev debug and user installation in the [README.rst](https://github.com/planetfederal/qgis-geogiglight-plugin/blob/master/README.rst). It points out to having a working installation of [geogig](http://geogig.org/) and for dev or manual build purposes it uses ```paver```. You can checkout the ```qgis3``` branch python3 compatibility

**Comment by tuannvapj** [comment]
> Hello @tuannvapj the repository [referenced](https://github.com/planetfederal/qgis-geogiglight-plugin) has guidelines on how to build and use this plugin. the required prerequisites for dev debug and user installation in the [README.rst](https://github.com/planetfederal/qgis-geogiglight-plugin/blob/master/README.rst). It points out to having a working installation of [geogig](http://geogig.org/) and for dev or manual build purposes it uses `paver`. You can checkout the `qgis3` branch python3 compatibility

Hi @koyo-jakanees, appreciate you reply, I just quite not understand and hope you could let me know
1) let's suppose I have clone [plugin](https://github.com/planetfederal/qgis-geogiglight-plugin) from github
2) I have run successfully in QGIS application
3) What I want, It should have the way to manage to debug inside code I have cloned ( but you know in the mean time, when I run plugin in QGIS). **Now I want to put some break-point with VSCODE or PyCharm - in order to clearly understanding which things are happening inside raw code**
Target: We need to deep and dive to plug in in the future to develop and support our particular need

Thanks

**Comment by koyo-jakanees** [comment]
> > Hello @tuannvapj the repository [referenced](https://github.com/planetfederal/qgis-geogiglight-plugin) has guidelines on how to build and use this plugin. the required prerequisites for dev debug and user installation in the [README.rst](https://github.com/planetfederal/qgis-geogiglight-plugin/blob/master/README.rst). It points out to having a working installation of [geogig](http://geogig.org/) and for dev or manual build purposes it uses `paver`. You can checkout the `qgis3` branch python3 compatibility
> 
> Hi @koyo-jakanees, appreciate you reply, I just quite not understand and hope you could let me know
> 
> 1. let's suppose I have clone [plugin](https://github.com/planetfederal/qgis-geogiglight-plugin) from github
> 2. I have run successfully in QGIS application
> 3. What I want, It should have the way to manage to debug inside code I have cloned ( but you know in the mean time, when I run plugin in QGIS). **Now I want to put some break-point with VSCODE or PyCharm - in order to clearly understanding which things are happening inside raw code**
>    Target: We need to deep and dive to plug in in the future to develop and support our particular need
> 
> Thanks

@tuannvapj responding to the third concern.  Depending on your workflow i have collected a few resources/ref docs that might suit your specific workflow, More of a General response. 
1. [QGIS docs ``IDE settings for writing and debugging python plugins``](https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/plugins/ide_debugging.html "general debugging tips for various IDEs") you can add ``scriptrunner3`` and/or ``Remote Debug`` qgis plugins but the listed two in the docs should suffice
2. [QGIS  wiki for debugging  C++ plugins using GDB](https://issues.qgis.org/projects/qgis/wiki/How_to_debug_QGIS_Plugins "Might not be very useful for your case")
3. [StackExchange  question ](https://gis.stackexchange.com/questions/41844/how-to-debug-a-qgis-python-plugin-with-popups "Manully set up QgsMessage box, similar to python print")
4. [Stack exchange QGIS3 plugin](https://gis.stackexchange.com/questions/327403/debug-qgis3-plugin-with-visual-studio-code "might have links usefull")
5. UPDATE: [VS Code + Mac OSx  gist guide](https://gist.github.com/AsgerPetersen/9ea79ae4139f4977c31dd6ede2297f90)

The links are general guidelines and not to any specific plugin. Using your IDE features for debugging or pdb. I'd highly recommend going through the first one. And hopefully this would be helpful for any future plugins you intend on developing

**Comment by tuannvapj** [comment]
@koyo-jakanees Thanks so much. 
I use a Remote Debug in Visual Studio Code (follow the https://gist.github.com/AsgerPetersen/9ea79ae4139f4977c31dd6ede2297f90) to Debugging.
