### ISSUE TITLE
GeoGig FeatureInfo Tool does not work with fid after adding a new feature

### ISSUE THREAD

**Issue by elpaso** [boundlessgeo/qgis-geogiglight-plugin#17]
Open `ne_countries.gpkg` in QGIS and add to a geogig repo
Add a new feature and sync 
use the info tool on the new feature

![image](https://cloud.githubusercontent.com/assets/142164/16872022/93e71d0a-4a8a-11e6-9a9f-44798b27d667.png)

The fid mapping is missing in `ne_countries_fid`

**Comment by volaya** [comment]
fixed in https://github.com/boundlessgeo/qgis-geogiglight-plugin/commit/a8cab8e633faf52dc85d9b78498b350a6aa4d4dd
