### ISSUE TITLE
Error when deleting layer

### ISSUE THREAD

**Issue by volaya** [boundlessgeo/qgis-geogiglight-plugin#2]
HTTPError: 400 Client Error: Bad Request for url: http://localhost:8182/repos/repo/remove?path=surface_water_sewer&output_format=json&transactionId=0a903d53-e7eb-4640-82d7-7f374a4695cc&recursive=true

**Comment by gioman** [comment]
not sure if this https://github.com/boundlessgeo/qgis-geogiglight-plugin/issues/37 is a different issue.

**Comment by gioman** [comment]
@volaya is this already solved or is something that I have not yet spotted myself?

**Comment by volaya** [comment]
solved already
