### ISSUE TITLE
Connection to repository is lost if refreshing list with server down

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#28]
If refreshing the list of geogig repositories when a server is down then the connection is removed from the list. Then if the server is started and  the list is refreshed again the connection previously removed do not show anymore.

**Comment by volaya** [comment]
in any case, https://github.com/boundlessgeo/qgis-geogiglight-plugin/commit/30525f0af0d878998e9994bf2087c9edfe6345c6 should fix that, since now all endpoints are shown in the tree, even if they are wrong or the server is down

**Comment by gioman** [comment]
> Not able to reproduce. I turn of the server and refresh, and the repos tree gets empty, but when i turn it back on and refresh again, all the repos re-appear. Had a look at the code and didnt see any place where the repo endpoint are deleted in case of failure.

I tested again now, before updating the plugin to the latest changes (so with the same code base as I tested yesterday) and I was not able to replicate the issue... Anyway with your latest change to me the behavior is more consistent (for example comparing with other places in QGIS where there are connections to a server/DB).

**Comment by volaya** [comment]
Great.  You cann close the issue if this is resolved.

**Comment by gioman** [comment]
> Great. You can close the issue if this is resolved.

done.
