### ISSUE TITLE
python error when clicking on "show local changes"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#29]
Edit a geogig layer, save edits, then in the contextual menu choose

geogig > show local changes

Plugin version: 1.0-20160720-342d01cc7f1f2b21a9abe90c346a836a31a1c2c7
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\layeractions.py", line 198, in showLocalChanges
    dlg = LocalDiffViewerDialog(iface.mainWindow(), layer)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\localdiffviewerdialog.py", line 75, in __init__
    self.computeDiffs()
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\localdiffviewerdialog.py", line 131, in computeDiffs
    self.changes = self.localChanges(self.layer)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\localdiffviewerdialog.py", line 188, in localChanges
    qgsfeature = list(layer.getFeatures(request))[0]
IndexError: list index out of range

**Comment by volaya** [comment]
some questions

What is the change that you do? addition, removal, change?

the geopackage that you are importing has an fid field used as Primery Key or has a different attribute name?

**Comment by gioman** [comment]
Hi @volaya the change was the addition of a new feature (polygon). There is a "fid" field that I'm seeing is correctly auto-filled (the field is only visible in DB Manager, but that is expected I guess).

**Comment by gioman** [comment]
> Can you send me the layer that causes that issue? If possible, with the polygon addition, but before you sync it with the repo, so it still causes the problem

@volaya sent now.

**Comment by volaya** [comment]
I suspect this might have been caused by fid mappings removed when updating the layer (which is fixed now). Will keep on trying to reproduce the error

**Comment by gioman** [comment]
Tested on the latest code revision and now a meaningful error message dialog is shown. Fix confirmed.
