### ISSUE TITLE
Additional warning when deleting a repo

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#34]
Deleting repositories via geogig Web-api has apperently been fixed and now is working also from within the plugin.

But this is done with no additional warning (ex: "warning: you are deleting a repository and all data in it"), exactly the same way as the user can delete a connection, that do not cause any data to be deleted.

**Comment by volaya** [comment]
There is already a warning message. See here:

https://github.com/boundlessgeo/qgis-geogiglight-plugin/blob/master/geogig/gui/dialogs/navigatordialog.py#L241

It seems to be working correctly. Can your confirm that in the latest version you can delete a repo without seeing any warning?

**Comment by gioman** [comment]
@volaya yes you are right. I suggest here https://github.com/boundlessgeo/qgis-geogiglight-plugin/pull/36 a slightly more verbose wording as it is not clear (at least at the beginning) that such action implies data deletion.
