### ISSUE TITLE
Use same colors in map view/table view in the geometry comparison tool

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#42]
In map view it would be good to use the same bright green/red used in table view.
I also wonder if in table view we should not use the same wording used in the "merge conflicts" tools, so local/remote instead of "base geometry/compare geometry".

![screenshot from 2016-07-27 18-42-05](https://cloud.githubusercontent.com/assets/1951107/17185744/3121786a-542a-11e6-976c-a9eaaef5962f.png)

![screenshot from 2016-07-27 18-42-09](https://cloud.githubusercontent.com/assets/1951107/17185746/331743f2-542a-11e6-8fac-685dded4ddc7.png)

**Comment by volaya** [comment]
I have changed the wording. If you want to change the styles, you can just modify the files referenced here (all in the 'resources' folder)

https://github.com/boundlessgeo/qgis-geogiglight-plugin/blob/master/geogig/gui/dialogs/geometrydiffviewerdialog.py#L36-L41
