### ISSUE TITLE
Changing to specific version in specific branch

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#50]
- Do a "create a new branch at this version..."

- Now you have two branches and in both you have at least (usually more) versions with same description message, commit id, tags etc.

- now click on "change to a different version..."

- choosing a branch will change to the last version available in that branch, with no clear way how to choose to a specific version in that specific branch

- moreover trying to "change to a different version..." by tag of version name does not seems to take into account that now the same tags/description messages are represented in more than 1 branch.

**Comment by gioman** [comment]
moreover when "change to a different version..." when choosing the option for version names it seems that the names shown are only the ones from the very first branch.

**Comment by gioman** [comment]
another note: when having more than one branch, then "add to QGIS" in repository summary is not immediately clear what layer from what branch has been added.

**Comment by volaya** [comment]
The version can now be selected in a history tree dialog. Please, test and close if solved

**Comment by gioman** [comment]
brillant!
