### ISSUE TITLE
in repository history add layer name along with description message

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#53]
It seems that in the GG workflow it will not be unusual to have users use the same (or very similar) description names for different geopackage layers.

At this moment in plugin history panel only the message is shown, and this can cause confusion about what specific layer is that version about.

**Comment by volaya** [comment]
You mean adding which layer from the repo has been affected by each commit?

Using the plugin, each commit updates a single tree (layer), but geogig support commits that affect several ones...so a repo might have several layers changed in one single version

**Comment by gioman** [comment]
@volaya I mean something relatively simple (from a user point of view of course), see attached image

![screenshot from 2016-07-28 14-45-59](https://cloud.githubusercontent.com/assets/1951107/17214757/55cd5cc6-54d2-11e6-8d5f-385c6132b00b.png)

two different layers imported in the same repo/branch, both with the same "Initial" message. Then 1 change done to each layer, both committed with the same message. To understand what layer correspond to what message the user has to open "show changes..." that is a not very convenient. I was suggesting that eventually after the message it could be added inside parenthesis the layer name.

But I'm not sure if I get completely what do you mean above, so maybe the suggestions does not make sense?

**Comment by volaya** [comment]
ISn't that the responsability of the committer, to provide a more descriptive message?

In any case, seems to be hard to implement, since the log operation doesnt return that information. That means that a separate api call should be done for each commit, to get the name of the modified layer(s). That might make it very slow to create the versions tree...

**Comment by gioman** [comment]
> ISn't that the responsability of the committer, to provide a more descriptive message?

sounds reasonable, better add a note in the docs?

**Comment by gioman** [comment]
> better add a note in the docs?

thinking about that... seems unnecessary. The doc already includes the text about the description message and also tags seems a suitable way to allow user recognize better edits/layers.
