### ISSUE TITLE
when "change to a different version" do not show tags and versions of other layers

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#56]
When doing "change to a different version" the user can choose among tags and version names of layers that are not the one being used. I'm not sure if this makes any sense.

If the users force "change to a different version" to a version that is in fact about another layer there is no error message. In message bar it shows a message like 

GeoGig: Layer has been updated to version 5ca4edb3fa418d4c848b375ea83da6969b9075dd

which I don't understand what sense makes.

**Comment by volaya** [comment]
It makes sense reverting to a version even if it doesnt affect the layer (at least, sense from the geogig point of view). Think about git. You can revert your git working tree to any version, even if that version did not introduced a change to a given file. That file would be updated to the state it had in that version (even if that's the same state it had in the parent commit or many commits ago in case it hasn't been changed in a while)

Anyway, the idea is good, and I can show only commits that mean a change to the layer.

**Comment by gioman** [comment]
> It makes sense reverting to a version even if it doesnt affect the layer (at least, sense from the geogig point of view). Think about git. You can revert your git working tree to any version, even if that version did not introduced a change to a given file. That file would be updated to the state it had in that version (even if that's the same state it had in the parent commit or many commits ago in case it hasn't been changed in a while)

got it


> Anyway, the idea is good, and I can show only commits that mean a change to the layer.

agree, it think it makes much more sense for the common users.
