### ISSUE TITLE
if a layer was already added to a repository is not possible to add it again to a different repo

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#57]
See attached image

![screenshot from 2016-07-28 15-18-42](https://cloud.githubusercontent.com/assets/1951107/17216171/710c2ae4-54d7-11e6-8b87-46c0e1315e6d.png)

the layer "ponts" is already in "repos2", and if I want to add it to "repos" I'm not presented with the appropriate option when right clicking in legend > geogig.

If clicking the button "add layer to repository..." it also not possible, as the message seems to suggest that there are no geopackages layers in the project, when in fact there are.

![screenshot from 2016-07-28 15-28-37](https://cloud.githubusercontent.com/assets/1951107/17216328/2047e142-54d8-11e6-877a-6c51666067af.png)

**Comment by volaya** [comment]
A layer can only belong to onerepo. The layer file keeps info about the commit it represents in the repo, so no way we can have that info for 2 layers. You should clone the layer and then add that cloned one to the repo.

Think about a file in git...it can only be in one repo

Any ideas on how to let the user know about that in the most intuitive way.

**Comment by gioman** [comment]
> A layer can only belong to onerepo. The layer file keeps info about the commit it represents in the repo, so no way we can have that info for 2 layers. You should clone the layer and then add that cloned one to the repo.
> 
> Think about a file in git...it can only be in one repo

ok. In this case I was just thinking as a final user with no knowledge of versioning stuff :)



> Any ideas on how to let the user know about that in the most intuitive way.

then if possible I would just change the message returned by the button "add layer to repository..." for this specific case. Then we can just document that a specific geopackages datasources can be added to just one repo. Sounds ok for you?

**Comment by gioman** [comment]
> then if possible I would just change the message returned by the button "add layer to repository..." for this specific case. Then we can just document that a specific geopackages datasources can be added to just one repo. Sounds ok for you?

that of course was already done in https://github.com/boundlessgeo/qgis-geogiglight-plugin/issues/58

**Comment by gioman** [comment]
I filed a ticket about adding a note in docs for this behavior/property, so I think we can close this.
