### ISSUE TITLE
base layers do not show in "merge conflicts" dialog

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#74]
Maybe I'm missing something simple, but regardless the CRS of the QGIS project (if that matters) I'm unable to see both OSM or Google base layers in the "merge conflicts" dialog.

**Comment by volaya** [comment]
base layers is actually giving some issues, and i removed it long time ago from the diff viewer. I think it makes sense to remove it also from the conflict dialog, since it doesn't really make a big difference.

Ideas?

**Comment by gioman** [comment]
> Ideas?

Is allowing the possibility to render a layer from the QGIS project as problematic as rendering this base layers? If no then it could be worth adding this functionality, otherwise I guess that is better to remove his control.

**Comment by volaya** [comment]
Sounds like a good idea. I will remove this for now, and then we can think about adding some control to add project layers
